include hyde.conf
# This is the configuration file for kitty terminal
font_family JetBrainsMono Nerd Font
font_size 12.5
enable_audio_bell no
window_padding_width 2
cursor_trail 1
cursor_shape beam
include onedark.conf
background_opacity 0.60
# BEGIN_KITTY_THEME
# Neowave
#include kyotonight.conf
include Neowave.conf
# END_KITTY_THEME

cursor_shape beam
shell_integration no-cursor
