# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here
# See https://wiki.hyprland.org/Configuring for more information

# // █ █▄░█ █▀█ █░█ ▀█▀
# // █ █░▀█ █▀▀ █▄█ ░█░

$CURSOR_THEME=Sweet-cursors
$CURSOR_SIZE=24
$ICON_THEME=BeautySolar
exec = gsettings set org.gnome.desktop.interface icon-theme $ICON_THEME
exec = gsettings set org.gnome.desktop.interface cursor-theme $CURSOR_THEME
exec = gsettings set org.gnome.desktop.interface cursor-size 24

env = QT_QPA_PLATFORMTHEME,qt5ct

input {
    sensitivity = 10
    touchpad {
        natural_scroll = no
    }
}

gestures {
#     workspace_swipe = true
#     workspace_swipe_fingers = 3
}

misc {
    # enable_swallow = true
    # swallow_regex = (foot|kitty|allacritty|Alacritty|ghostty|Ghostty|org.wezfurlong.wezterm)
}

ecosystem {
    no_update_news = true
}

general {
    gaps_in = 4
    gaps_out = 6
    border_size = 2
    col.active_border = rgba(90ceaaff) rgba(ecd3a0ff) 45deg
    col.inactive_border = rgba(86aaeccc) rgba(93cee9cc) 45deg
    layout = dwindle
    resize_on_border = true
}

group {
    col.border_active = rgba(90ceaaff) rgba(ecd3a0ff) 45deg
    col.border_inactive = rgba(86aaeccc) rgba(93cee9cc) 45deg
    col.border_locked_active = rgba(90ceaaff) rgba(ecd3a0ff) 45deg
    col.border_locked_inactive = rgba(86aaeccc) rgba(93cee9cc) 45deg
}

decoration {
    rounding = 4
    shadow {
        enabled = false
    }
    blur {
        enabled = yes
        size = 2
        passes = 3
        new_optimizations = on
        ignore_opacity = on
        xray = false
    }
}

